spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    click:
      driverClassName: ru.yandex.clickhouse.ClickHouseDriver
      url: jdbc:clickhouse://192.168.0.130:8123/default
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    template-loader-path: classpath:/templates/
    suffix: .ftl
server:
  tomcat:
    uri-encoding: utf-8
  port: 8088

mybatis:
  type-aliases-package: com.ck.bean
  mapper-locations: classpath:/mapper/*.xml